# shallow clone
clone_depth: 10

os: Visual Studio 2015

platform:
  - x64
  - Win32

environment:
  matrix:
   - Toolset: v140
   - Toolset: v120

configuration:
  - Debug

install:
  - git submodule update --init --recursive

before_build:
- ps: |
    md build
    cd build
    $generator = switch ($env:TOOLSET)
    {
        "v140" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
    }
    if ($env:PLATFORM -eq "x64")
    {
        $generator = "$generator Win64"
    }
    cmake -G "$generator"  ..
    cd ..

build:
  verbosity: minimal

build_script:
- ps: |
    cd build
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
test_script:
- ps: |
    cd tests
    & .\$env:CONFIGURATION\test_all.exe
